-- Foundation schema: identity, platform registry, trading/AI control plane.
create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;
grant usage on schema app_private to authenticated;

create type public.execution_class as enum ('FULL_AUTO','LIMITED_AUTO','COPILOT','UNSUPPORTED');
create type public.automation_mode as enum ('ANALYSIS','PAPER','APPROVAL_REQUIRED','BOUNDED_AUTO');
create type public.trade_action as enum ('LONG','SHORT','BUY','SELL','REDUCE','CLOSE','WAIT','NO_TRADE');
create type public.risk_decision_status as enum ('APPROVE','MODIFY','REJECT');
create type public.order_status as enum ('PENDING','SUBMITTED','PARTIALLY_FILLED','FILLED','CANCELLED','REJECTED','EXPIRED');
create type public.position_side as enum ('LONG','SHORT');
create type public.evidence_level as enum ('CONFIRMED','HIGHLY_LIKELY','SUSPICIOUS','PROJECT_FAILURE','UNKNOWN');
create type public.feature_status as enum ('NOT_STARTED','SCAFFOLDED','IN_PROGRESS','IMPLEMENTED','TESTED','BLOCKED');
create type public.health_status as enum ('HEALTHY','DEGRADED','UNHEALTHY','UNKNOWN');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  experience_level text not null default 'BEGINNER',
  onboarding_complete boolean not null default false,
  default_automation_mode public.automation_mode not null default 'ANALYSIS',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.user_settings (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, locale text not null default 'en', timezone text not null default 'UTC', beginner_mode boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, role_key text not null, created_at timestamptz not null default now(), unique(user_id,role_key));
create table public.admin_roles (id uuid primary key default gen_random_uuid(), role_key text not null unique, name text not null, created_at timestamptz not null default now());
create table public.admin_permissions (id uuid primary key default gen_random_uuid(), permission_key text not null unique, description text not null, created_at timestamptz not null default now());
create table public.admin_role_permissions (admin_role_id uuid not null references public.admin_roles(id) on delete cascade, permission_id uuid not null references public.admin_permissions(id) on delete cascade, primary key(admin_role_id,permission_id));
create table public.admin_memberships (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, admin_role_id uuid not null references public.admin_roles(id), status text not null default 'ACTIVE' check(status in ('ACTIVE','SUSPENDED','REVOKED')), mfa_required boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.trading_platforms (id uuid primary key default gen_random_uuid(), platform_key text not null unique, name text not null, family text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.platform_capabilities (
 id uuid primary key default gen_random_uuid(), platform_id uuid not null references public.trading_platforms(id) on delete cascade, version int not null default 1, execution_class public.execution_class not null default 'COPILOT', market_data boolean not null default false, websocket boolean not null default false, historical_data boolean not null default false, account_read boolean not null default false, spot boolean not null default false, margin boolean not null default false, futures boolean not null default false, perpetuals boolean not null default false, options boolean not null default false, market_order boolean not null default false, limit_order boolean not null default false, stop_loss boolean not null default false, take_profit boolean not null default false, trailing_stop boolean not null default false, partial_close boolean not null default false, paper_trading boolean not null default false, automated_execution boolean not null default false, wallet_connection boolean not null default false, sniping boolean not null default false, withdrawal_required boolean not null default false check(withdrawal_required=false), policy_reviewed boolean not null default false, official_policy_source text, policy_reviewed_at timestamptz, known_limitations jsonb not null default '[]'::jsonb, unique(platform_id,version)
);
create table public.platform_connections (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, platform_id uuid not null references public.trading_platforms(id), credential_reference text, account_external_ref text, automation_mode public.automation_mode not null default 'ANALYSIS', withdrawal_permission boolean not null default false check(withdrawal_permission=false), status text not null default 'DISCONNECTED', last_health_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.trading_accounts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, platform_connection_id uuid not null references public.platform_connections(id) on delete cascade, account_label text, currency text not null default 'USD', is_paper boolean not null default true, external_account_ref text, created_at timestamptz not null default now());

create table public.portfolios (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null default 'Primary', base_currency text not null default 'USD', created_at timestamptz not null default now());
create table public.portfolio_allocations (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, portfolio_id uuid not null references public.portfolios(id) on delete cascade, asset_key text not null, target_pct numeric(8,5) not null check(target_pct>=0 and target_pct<=1), created_at timestamptz not null default now());
create table public.positions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, portfolio_id uuid references public.portfolios(id) on delete set null, trading_account_id uuid references public.trading_accounts(id) on delete set null, platform_id uuid references public.trading_platforms(id), instrument_key text not null, side public.position_side not null, quantity numeric not null check(quantity>=0), entry_price numeric, current_price numeric, leverage numeric not null default 1 check(leverage>=1), status text not null default 'OPEN', opened_at timestamptz not null default now(), closed_at timestamptz);
create table public.orders (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, trading_account_id uuid references public.trading_accounts(id), trade_intent_id uuid, platform_id uuid references public.trading_platforms(id), instrument_key text not null, side text not null, order_type text not null, quantity numeric not null check(quantity>0), limit_price numeric, stop_price numeric, status public.order_status not null default 'PENDING', idempotency_key text not null unique, external_order_ref text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.trades (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, order_id uuid references public.orders(id), position_id uuid references public.positions(id), quantity numeric not null, price numeric not null, fee numeric not null default 0, slippage_bps numeric, executed_at timestamptz not null default now());
create table public.trade_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, trade_id uuid references public.trades(id) on delete cascade, order_id uuid references public.orders(id) on delete cascade, event_type text not null, payload jsonb not null default '{}'::jsonb, event_at timestamptz not null default now());

create table public.trade_intents (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, account_id uuid references public.trading_accounts(id), platform_id uuid references public.trading_platforms(id), instrument_key text not null, venue_symbol text not null, market_type text not null, action public.trade_action not null, strategy_key text not null, strategy_version text not null, market_regime text not null, order_type text, proposed_entry numeric, proposed_size numeric not null check(proposed_size>=0), stop_invalidation numeric, profit_targets jsonb not null default '[]'::jsonb, profit_protection_policy jsonb not null default '{}'::jsonb, max_slippage_bps numeric not null default 0, max_fee_bps numeric not null default 0, leverage numeric not null default 1, confidence numeric not null check(confidence>=0 and confidence<=1), calibration_metadata jsonb not null default '{}'::jsonb, specialist_scores jsonb not null default '{}'::jsonb, news_risk text not null default 'UNKNOWN', liquidity_state text, token_security_risk numeric, creator_risk numeric, expires_at timestamptz not null, model_versions jsonb not null default '{}'::jsonb, reason_summary text not null, schema_version int not null default 1, created_at timestamptz not null default now());
create table public.trade_evidence (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, trade_intent_id uuid not null references public.trade_intents(id) on delete cascade, source text not null, source_uri text, source_timestamp timestamptz not null, received_timestamp timestamptz not null default now(), freshness_ms bigint, asset_relevance numeric check(asset_relevance between 0 and 1), confidence numeric check(confidence between 0 and 1), source_quality numeric check(source_quality between 0 and 1), evidence jsonb not null default '{}'::jsonb);
create table public.trade_decisions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, trade_intent_id uuid not null references public.trade_intents(id) on delete cascade, status public.risk_decision_status not null, approved_size numeric not null default 0, reasons jsonb not null default '[]'::jsonb, deterministic_policy_version text not null, portfolio_snapshot jsonb not null default '{}'::jsonb, capability_snapshot jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table public.orders add constraint orders_trade_intent_fk foreign key(trade_intent_id) references public.trade_intents(id) on delete set null;

create table public.risk_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, mode text not null default 'CONSERVATIVE', trading_capital numeric not null default 0 check(trading_capital>=0), max_acceptable_loss numeric not null default 0 check(max_acceptable_loss>=0), profit_target numeric, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.risk_limits (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, risk_profile_id uuid not null references public.risk_profiles(id) on delete cascade, max_risk_per_trade numeric not null default 0, max_daily_loss numeric not null default 0, max_drawdown numeric not null default 0, max_leverage numeric not null default 1, max_positions int not null default 1, max_correlated_exposure numeric not null default 0, max_platform_exposure numeric not null default 0, max_asset_exposure numeric not null default 0, max_memecoin_exposure numeric not null default 0, max_slippage_bps numeric not null default 0, min_liquidity numeric not null default 0, min_confidence numeric not null default 0, min_expected_edge numeric not null default 0, max_spread_bps numeric not null default 0, news_restrictions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.risk_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, severity text not null, event_type text not null, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create table public.strategies (id uuid primary key default gen_random_uuid(), strategy_key text not null unique, name text not null, description text not null, enabled boolean not null default false, created_at timestamptz not null default now());
create table public.strategy_versions (id uuid primary key default gen_random_uuid(), strategy_id uuid not null references public.strategies(id) on delete cascade, version text not null, config jsonb not null default '{}'::jsonb, deployment_status text not null default 'RESEARCH', created_at timestamptz not null default now(), unique(strategy_id,version));
create table public.strategy_assignments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, strategy_version_id uuid not null references public.strategy_versions(id), enabled boolean not null default false, allocation_limit numeric not null default 0, created_at timestamptz not null default now());
create table public.models (id uuid primary key default gen_random_uuid(), model_key text not null unique, name text not null, task text not null, created_at timestamptz not null default now());
create table public.model_versions (id uuid primary key default gen_random_uuid(), model_id uuid not null references public.models(id) on delete cascade, version text not null, artifact_ref text, dataset_lineage jsonb not null default '{}'::jsonb, deployment_status text not null default 'RESEARCH', created_at timestamptz not null default now(), unique(model_id,version));
create table public.model_metrics (id uuid primary key default gen_random_uuid(), model_version_id uuid not null references public.model_versions(id) on delete cascade, metric_key text not null, metric_value numeric not null, dimensions jsonb not null default '{}'::jsonb, measured_at timestamptz not null default now());

create table public.market_instruments (id uuid primary key default gen_random_uuid(), canonical_key text not null unique, market_type text not null, base_asset text, quote_asset text, metadata jsonb not null default '{}'::jsonb);
create table public.market_symbols (id uuid primary key default gen_random_uuid(), platform_id uuid not null references public.trading_platforms(id) on delete cascade, instrument_id uuid not null references public.market_instruments(id) on delete cascade, venue_symbol text not null, contract_metadata jsonb not null default '{}'::jsonb, unique(platform_id,venue_symbol));
create table public.symbol_mappings (id uuid primary key default gen_random_uuid(), instrument_id uuid not null references public.market_instruments(id) on delete cascade, source text not null, source_symbol text not null, metadata jsonb not null default '{}'::jsonb, unique(source,source_symbol));
create table public.watchlists (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table public.watchlist_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, watchlist_id uuid not null references public.watchlists(id) on delete cascade, instrument_id uuid not null references public.market_instruments(id), created_at timestamptz not null default now(), unique(watchlist_id,instrument_id));
create table public.alerts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, alert_type text not null, conditions jsonb not null default '{}'::jsonb, enabled boolean not null default true, mandatory boolean not null default false, created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, category text not null, title text not null, body text not null, payload jsonb not null default '{}'::jsonb, read_at timestamptz, created_at timestamptz not null default now());
