-- Intelligence, paper trading, backtest, operations, feature registry.
create table public.news_events (id uuid primary key default gen_random_uuid(), source text not null, source_uri text, source_timestamp timestamptz not null, received_timestamp timestamptz not null default now(), headline text not null, event_type text, importance numeric, sentiment numeric, source_quality numeric, payload jsonb not null default '{}'::jsonb);
create table public.economic_events (id uuid primary key default gen_random_uuid(), provider text not null, event_key text not null, country text, currency text, event_time timestamptz not null, importance text, actual text, forecast text, previous text, payload jsonb not null default '{}'::jsonb, unique(provider,event_key,event_time));
create table public.news_asset_impacts (id uuid primary key default gen_random_uuid(), news_event_id uuid not null references public.news_events(id) on delete cascade, instrument_id uuid references public.market_instruments(id) on delete cascade, relevance numeric not null check(relevance between 0 and 1), directional_score numeric, confidence numeric check(confidence between 0 and 1));

create table public.tokens (id uuid primary key default gen_random_uuid(), chain_key text not null, contract_address text not null, symbol text, name text, decimals int, deployer_wallet text, created_at_chain timestamptz, metadata jsonb not null default '{}'::jsonb, unique(chain_key,contract_address));
create table public.token_security_reports (id uuid primary key default gen_random_uuid(), token_id uuid not null references public.tokens(id) on delete cascade, provider text not null, honeypot_risk numeric, sellable boolean, buy_tax numeric, sell_tax numeric, mint_authority boolean, freeze_authority boolean, liquidity_risk numeric, holder_concentration numeric, risk_score numeric, evidence jsonb not null default '{}'::jsonb, scanned_at timestamptz not null default now());
create table public.liquidity_snapshots (id uuid primary key default gen_random_uuid(), token_id uuid not null references public.tokens(id) on delete cascade, venue text, liquidity_usd numeric, price_impact_1pct numeric, lp_owner text, lp_lock_state text, captured_at timestamptz not null default now());
create table public.holder_snapshots (id uuid primary key default gen_random_uuid(), token_id uuid not null references public.tokens(id) on delete cascade, top_holders jsonb not null default '[]'::jsonb, top10_pct numeric, creator_pct numeric, bundled_pct numeric, sniper_pct numeric, captured_at timestamptz not null default now());
create table public.wallet_entities (id uuid primary key default gen_random_uuid(), chain_key text not null, address text not null, label text, entity_type text, confidence numeric check(confidence between 0 and 1), metadata jsonb not null default '{}'::jsonb, unique(chain_key,address));
create table public.wallet_relationships (id uuid primary key default gen_random_uuid(), from_wallet_id uuid not null references public.wallet_entities(id) on delete cascade, to_wallet_id uuid not null references public.wallet_entities(id) on delete cascade, relationship_type text not null, confidence numeric not null check(confidence between 0 and 1), evidence jsonb not null default '{}'::jsonb, observed_at timestamptz not null default now());
create table public.wallet_clusters (id uuid primary key default gen_random_uuid(), cluster_key text not null unique, confidence numeric not null check(confidence between 0 and 1), rationale jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.wallet_cluster_members (cluster_id uuid not null references public.wallet_clusters(id) on delete cascade, wallet_id uuid not null references public.wallet_entities(id) on delete cascade, confidence numeric not null check(confidence between 0 and 1), primary key(cluster_id,wallet_id));
create table public.creator_entities (id uuid primary key default gen_random_uuid(), display_label text, evidence_level public.evidence_level not null default 'UNKNOWN', reputation_score numeric, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.creator_wallet_links (id uuid primary key default gen_random_uuid(), creator_id uuid not null references public.creator_entities(id) on delete cascade, wallet_id uuid not null references public.wallet_entities(id) on delete cascade, confidence numeric not null check(confidence between 0 and 1), evidence jsonb not null default '{}'::jsonb);
create table public.projects (id uuid primary key default gen_random_uuid(), project_key text unique, name text not null, website text, github_url text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.creator_projects (id uuid primary key default gen_random_uuid(), creator_id uuid not null references public.creator_entities(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, relationship text not null, evidence_level public.evidence_level not null default 'UNKNOWN', confidence numeric check(confidence between 0 and 1), unique(creator_id,project_id));
create table public.creator_reputation_history (id uuid primary key default gen_random_uuid(), creator_id uuid not null references public.creator_entities(id) on delete cascade, score numeric, evidence_level public.evidence_level not null, rationale jsonb not null default '{}'::jsonb, recorded_at timestamptz not null default now());
create table public.project_authenticity_reports (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, evidence_level public.evidence_level not null default 'UNKNOWN', authenticity_score numeric, claim_checks jsonb not null default '[]'::jsonb, evidence jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.rug_events (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id), token_id uuid references public.tokens(id), evidence_level public.evidence_level not null, event_type text not null, evidence jsonb not null default '{}'::jsonb, occurred_at timestamptz, recorded_at timestamptz not null default now());
create table public.security_incidents (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id), token_id uuid references public.tokens(id), severity text not null, status text not null default 'OPEN', evidence jsonb not null default '{}'::jsonb, occurred_at timestamptz, created_at timestamptz not null default now());
create table public.scam_reports (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id), token_id uuid references public.tokens(id), source text not null, source_uri text, evidence_level public.evidence_level not null default 'UNKNOWN', evidence jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.sniper_activity (id uuid primary key default gen_random_uuid(), token_id uuid references public.tokens(id), wallet_id uuid references public.wallet_entities(id), activity_type text not null, amount numeric, confidence numeric check(confidence between 0 and 1), observed_at timestamptz not null default now(), evidence jsonb not null default '{}'::jsonb);
create table public.bot_activity (id uuid primary key default gen_random_uuid(), token_id uuid references public.tokens(id), wallet_id uuid references public.wallet_entities(id), bot_type text, confidence numeric check(confidence between 0 and 1), evidence jsonb not null default '{}'::jsonb, observed_at timestamptz not null default now());
create table public.mev_events (id uuid primary key default gen_random_uuid(), chain_key text not null, tx_hash text, event_type text not null, severity text, confidence numeric check(confidence between 0 and 1), evidence jsonb not null default '{}'::jsonb, observed_at timestamptz not null default now());

create table public.paper_accounts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null default 'Paper', base_currency text not null default 'USD', starting_equity numeric not null default 10000, current_equity numeric not null default 10000, created_at timestamptz not null default now());
create table public.paper_orders (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, paper_account_id uuid not null references public.paper_accounts(id) on delete cascade, trade_intent_id uuid references public.trade_intents(id), instrument_key text not null, side text not null, order_type text not null, quantity numeric not null, requested_price numeric, status public.order_status not null default 'PENDING', simulated_latency_ms int not null default 0, simulated_slippage_bps numeric not null default 0, created_at timestamptz not null default now());
create table public.paper_trades (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, paper_order_id uuid not null references public.paper_orders(id) on delete cascade, quantity numeric not null, fill_price numeric not null, fee numeric not null default 0, filled_at timestamptz not null default now());
create table public.backtests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, strategy_version_id uuid references public.strategy_versions(id), config jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.backtest_runs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, backtest_id uuid not null references public.backtests(id) on delete cascade, status text not null default 'QUEUED', metrics jsonb not null default '{}'::jsonb, assumptions jsonb not null default '{}'::jsonb, started_at timestamptz, completed_at timestamptz);
create table public.market_replay_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, start_time timestamptz not null, end_time timestamptz not null, status text not null default 'READY', config jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, plan_key text not null default 'FREE', status text not null default 'ACTIVE', current_period_end timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.kill_switches (
  id uuid primary key default gen_random_uuid(),
  scope_type text not null check(scope_type in ('GLOBAL','USER','ACCOUNT','PLATFORM','STRATEGY')),
  scope_ref text,
  mode text not null default 'STOP_NEW' check(mode in ('STOP_NEW','CLOSE_ONLY','CLOSE_ALL')),
  active boolean not null default false,
  reason text,
  activated_by uuid references auth.users(id) on delete set null,
  activated_at timestamptz,
  released_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(scope_type,scope_ref)
);
create unique index kill_switches_single_global on public.kill_switches(scope_type) where scope_type='GLOBAL';
create table public.account_trading_controls (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  trading_account_id uuid not null unique references public.trading_accounts(id) on delete cascade,
  suspended boolean not null default false,
  mode public.automation_mode not null default 'ANALYSIS',
  reason text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
create table public.system_settings (id uuid primary key default gen_random_uuid(), setting_key text not null unique, value jsonb not null, version int not null default 1, updated_by uuid references auth.users(id), updated_at timestamptz not null default now());
create table public.system_health (id uuid primary key default gen_random_uuid(), component text not null unique, status public.health_status not null default 'UNKNOWN', details jsonb not null default '{}'::jsonb, checked_at timestamptz not null default now());
create table public.provider_health (id uuid primary key default gen_random_uuid(), provider_key text not null unique, status public.health_status not null default 'UNKNOWN', latency_ms int, last_success_at timestamptz, last_error_at timestamptz, details jsonb not null default '{}'::jsonb, checked_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_user_id uuid references auth.users(id) on delete set null, actor_db_role text, action text not null, table_name text not null, row_id uuid, old_data jsonb, new_data jsonb, correlation_id text, created_at timestamptz not null default now());
create table public.feature_registry (id uuid primary key default gen_random_uuid(), feature_id text not null unique, feature_name text not null, description text not null, location text, backend_dependencies text, frontend_dependencies text, status public.feature_status not null default 'NOT_STARTED', test_status text not null default 'NOT_RUN', notes text, updated_at timestamptz not null default now());
